import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/common/header'
import Player from '@/components/common/Player'
import Sidebar from '@/components/common/Sidebar'
import MSWComponent from '@/components/mock-service/MSWComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWComponent>
          <main className="min-h-screen bg-color-background-primary p-2">
            <section className="grid">
              <div className="cursor-e-resize resize-x">
                <Sidebar />
              </div>
              <div className="">
                <Header />
                {children}
              </div>
              <div className="">
                <Player />
              </div>
            </section>
          </main>
        </MSWComponent>
      </body>
    </html>
  )
}
