import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/common/header'
import Player from '@/components/common/Player'
import Sidebar from '@/components/common/Sidebar'
import MSWComponent from '@/components/mock-service/MSWComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'asac-spotify-clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWComponent>
          <main className="bg-color-background-primary">
            <section className="h-screen grid grid-areas-destop grid-rows-layout grid-cols-layout p-2 gap-2">
              {/* <aside className="cursor-e-resize resize-x w-[280px] grid-in-left-sidebar"> */}
              <aside className="w-[280px] grid-in-left-sidebar">
                <Sidebar />
              </aside>
              {/* <div className="grid-in-main">
              </div> */}
              <div className="flex flex-col grid-in-main">
                <Header />
                {children}
              </div>
              {/* <aside className="cursor-e-resize resize-x grid-in-right-sidebar">
                <Sidebar />
              </aside> */}
              <div className="grid-in-now-playing-bar h-[72px]">
                <Player />
              </div>
            </section>
          </main>
        </MSWComponent>
      </body>
    </html>
  )
}
